<!doctype html>
<html lang="en">
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Order Status Report</title>
</head>
<body>
<div style="margin-top: 10px">Hello All,<br/>Greetings,&nbsp Please find Order Report below:</div>
<br/>
<div><b>Order Status Report Pie Chart: </b></div>
<img src='cid:identifier1234'>
<br/>
<br/>
<br/>
<div><b>Order Status Report Detailed Summary Table: </b></div>
<br/>
<table style="width:100%">
  <tr style="background-color:#0000FF">
    <th colspan="4">Order Types with Count</th>
  </tr>
  <tr>
    <th style="background-color:#ADD8E6">Order Types</th>
    <th style="background-color:#ADD8E6">ADD</th>
    <th style="background-color:#ADD8E6">CHANGE</th>
    <th style="background-color:#ADD8E6">DELETE</th>
  </tr>
  <tr>
    <th>Completed Orders</th>
    <td>${user.count}</td>
    <td>201</td>
    <td>17</td>
  </tr>
  <tr>
    <th>In-Progress Orders</th>
    <td>17</td>
    <td>52</td>
    <td>9</td>
  </tr>
  <tr>
    <th>Scheduled Orders</th>
    <td>11</td>
    <td>18</td>
    <td>1</td>
  </tr>
  <tr>
    <th>Errored Orders</th>
    <td>9</td>
    <td>12</td>
    <td>2</td>
  </tr>
  <tr>
    <th>Expired Orders</th>
    <td>5</td>
    <td>8</td>
    <td>2</td>
  </tr>
  <tr>
    <th>Total Orders</th>
    <td>142</td>
    <td>291</td>
    <td>31</td>
  </tr>
</table>
<br/>
<div> Have a nice day..!</div>
<br/>
<div> Thanks <br/> OpsCapgemini</div>
</body>
</html>